SITE_NAME = "CHAO.X"
SITE_LOGO_NAME = "CHAO.X"
SITE_COPYRIGHT_NAME = "CHAOX"

SITE_KEYWORDS = "ChaoX,Chao,node,vue,Python,Django,backend,blog,web,mysql,random thoughts,coding,One Piece"
SITE_DESCRIPTION = "This is a salted fish coder developed website which mainly records and shares coding notes, random thoughts."
SITE_URL = "https://chaox.me"

STATIC_FOLDER = "txt/static"
TEMPLATES_FOLDER = "txt/templates"


LINKS = [
    ['zhanghaoran.ren', 'http://blog.zhanghaoran.ren/'],
]

#ANALYTICS_CODE = """
#"""