SITE_NAME = "CHENN.ME"
SITE_LOGO_NAME = "CHENN.ME"
SITE_COPYRIGHT_NAME = "CHENN"

SITE_KEYWORDS = "CHENN,CHEN,Python,Django,backend,web,mysql,random thoughts,coding,One Piece"
SITE_DESCRIPTION = "Chenn's personal website which mainly records and shares coding notes, as well as life, reading and random thoughts."
SITE_URL = "https://chenn.me"

STATIC_FOLDER = "txt/static"
TEMPLATES_FOLDER = "txt/templates"

PAGINATION_NUM=10
LINKS = [
    ['zhanghaoran.ren', 'http://blog.zhanghaoran.ren/'],
]

#ANALYTICS_CODE = """
#"""