SITE_NAME = "ZORO.X"
SITE_LOGO_NAME = "ZORO.X"
SITE_COPYRIGHT_NAME = "ZOROX"

SITE_KEYWORDS = "zorox,node,vue,Python,Django,backend,blog,web,mysql,random thoughts,coding,One Piece,zoro"
SITE_DESCRIPTION = "This is a salted fish coder developed website which mainly records and shares coding notes, random thoughts."
SITE_URL = "https://zorox.me"

STATIC_FOLDER = "txt/static"
TEMPLATES_FOLDER = "txt/templates"


LINKS = [
    ['zhanghaoran.ren', 'http://blog.zhanghaoran.ren/'],
]

#ANALYTICS_CODE = """
#"""